@startuml

skinparam componentStyle uml1

component "Cloud Provider" {
    component "Discovery Document" <<API Spec>> as discdoc {
    }
    component "Resource API" <<API>> as api {
    }
}

package "InfraQL Application" {
    database "Local Backend" <<store>> as localdb { 
    }
    [LocalExecutor] <<component>> as localexec
    [RemoteExecutor] <<component>> as remoteexec
    [QueryPlanner] <<component>> as planner
    [QueryParser] <<component>> as parser
    [QueryPreProcessor] <<component>> as preprocessor
    [Driver] <<component>> as driver
}

interface " " as userint

discdoc -[hidden]D- api
userint -- driver : " query interface"
driver ~down~> preprocessor
preprocessor ~up~> parser
parser ~down~> planner
planner ~down~> localexec
planner ~up~> remoteexec
remoteexec ~down~> localdb
localexec ~up~> localdb

remoteexec -[hidden]U- discdoc
remoteexec -[hidden]R- api
remoteexec -(0- discdoc
remoteexec -(0- api

@enduml