/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// The Quick Starts category cards on /quick-starts carry the provider's icon.
// The icon (and its dark-mode treatment) comes from the provider catalog,
// src/configs/providers.json, keyed by the microsite slug, so the cards stay
// in step with the /providers tiles and the navbar dropdown.
const { PROVIDERS } = require('./src/lib/providers');

function providerIcon(slug) {
  const provider = PROVIDERS.find((p) => p.slug === slug);
  if (!provider) {
    throw new Error(`[sidebars] no provider with slug "${slug}" in src/configs/providers.json`);
  }
  return {
    icon: provider.icon,
    ...(provider.invertOnDark ? { invertOnDark: true } : {}),
  };
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    'installing-stackql',
    'ai-agents',
    'providers',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Core concepts and first steps: the resource hierarchy, running StackQL, using a provider, output modes, variables and templating',
        slug: '/getting-started',
      },
      items: [
        'getting-started/resource-hierarchy',
        'getting-started/using-stackql',
        'getting-started/using-a-provider',
        'getting-started/claude-desktop',
        'getting-started/output-modes',
        'getting-started/otel-recipes',
        'getting-started/variables',
        'getting-started/templating',
      ]
    },
    {
      type: 'category',
      label: 'Command Line Usage',
      link: {
        type: 'generated-index',
        title: 'Command Line Usage',
        description: 'The stackql command line: exec, shell, srv, mcp, registry and the global flags',
        slug: '/command-line-usage',
      },
      items: [
        'command-line-usage/exec',
        'command-line-usage/shell',
        'command-line-usage/srv',
        'command-line-usage/mcp',
        'command-line-usage/registry',
        'command-line-usage/global-flags',
      ]
    },
    {
      type: 'category',
      label: 'MCP',
      link: {
        type: 'doc',
        id: 'mcp/index',
      },
      items: [
        'mcp/server_info',
        'mcp/reload_credentials',
        'mcp/list_providers',
        'mcp/list_services',
        'mcp/list_resources',
        'mcp/list_methods',
        'mcp/describe_method',
        'mcp/list_registry',
        'mcp/pull_provider',
        'mcp/validate_select_query',
        'mcp/run_select_query',
        'mcp/run_mutation_query',
        'mcp/run_lifecycle_operation',
        {
          type: 'category',
          label: 'Embedded',
          link: {
            type: 'doc',
            id: 'mcp/embedded/index',
          },
          items: [
            'mcp/embedded/go',
            'mcp/embedded/rust',
            'mcp/embedded/swift',
            'mcp/embedded/kotlin',
            'mcp/embedded/dotnet',
            'mcp/embedded/gleam',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Language Specification',
      items: [
        'language-spec/select',
        'language-spec/insert',
        'language-spec/update',
        'language-spec/delete',
        'language-spec/replace',
        'language-spec/show',
        'language-spec/describe',
        'language-spec/exec',
        'language-spec/createview',
        'language-spec/refreshview',
        'language-spec/dropview',
        'language-spec/with',
        'language-spec/registry',
        'language-spec/windowing_functions',
        {
          type: 'category',
          label: 'Built-in Functions',
          items: [{type: 'autogenerated', dirName: 'language-spec/functions'}]
        },
        'language-spec/data-types',
        'language-spec/lexical-structure',
        'language-spec/keywords',
        'language-spec/utility-commands',
      ]
    },  
    {
      type: 'category',
      label: 'Developers',
      items: [{type: 'autogenerated', dirName: 'developers'}]
    },
    {
      // Formerly "Tutorials" at /docs/tutorials. Renamed so that "Tutorials"
      // can mean the blog tutorials section (/blog/tutorials). Old URLs are
      // 301'd in netlify.toml.
      type: 'category',
      label: 'Quick Starts',
      link: {
        type: 'generated-index',
        title: 'Quick Starts',
        description: 'StackQL quick starts, how-tos, practical examples and use cases',
        slug: '/quick-starts',
        keywords: ['quick starts', 'quickstarts', 'guides', 'how-tos', 'examples', 'use cases'],
        image: '/img/stackql-cover.png',
      },
      items: [
        {
          type: 'category',
          label: 'AWS',
          customProps: providerIcon('aws'),
          description: 'Practical examples and use cases specific to AWS',
          link: {
            type: 'generated-index',
            title: 'AWS Quick Starts',
            description: 'Practical examples and use cases specific to AWS',
            slug: '/quick-starts/aws',
          },
          items: [{ type: 'autogenerated', dirName: 'quick-starts/aws' }],
        },
        {
          type: 'category',
          label: 'Microsoft Azure',
          customProps: providerIcon('azure'),
          description: 'Practical examples and use cases specific to Azure',
          link: {
            type: 'generated-index',
            title: 'Azure Quick Starts',
            description: 'Practical examples and use cases specific to Azure',
            slug: '/quick-starts/azure',
          },
          items: [{ type: 'autogenerated', dirName: 'quick-starts/azure' }],
        },
        {
          type: 'category',
          label: 'Google Cloud Platform',
          customProps: providerIcon('google'),
          description: 'Practical examples and use cases specific to Google Cloud',
          link: {
            type: 'generated-index',
            title: 'Google Quick Starts',
            description: 'Practical examples and use cases specific to Google Cloud',
            slug: '/quick-starts/google',
          },
          items: [{ type: 'autogenerated', dirName: 'quick-starts/google' }],
        },
        {
          type: 'category',
          label: 'GitHub',
          customProps: providerIcon('github'),
          description: 'Practical examples and use cases specific to GitHub',
          link: {
            type: 'generated-index',
            title: 'GitHub Quick Starts',
            description: 'Practical examples and use cases specific to GitHub',
            slug: '/quick-starts/github',
          },
          items: [{ type: 'autogenerated', dirName: 'quick-starts/github' }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
