/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    'installing-stackql',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/resource-hierarchy',
        'getting-started/using-stackql',
        'getting-started/using-a-provider',
        'getting-started/output-modes',
        'getting-started/variables',
        'getting-started/templating',
      ]
    },
    {
      type: 'category',
      label: 'Command Line Usage',
      items: [
        'command-line-usage/exec',
        'command-line-usage/shell',
        'command-line-usage/srv',
        'command-line-usage/registry',
        'command-line-usage/global-flags',
      ]
    },
    {
      type: 'category',
      label: 'Language Specification',
      items: [
        'language-spec/select',
        'language-spec/show',
        'language-spec/describe',
        'language-spec/createview',
        'language-spec/insert',
        'language-spec/delete',
        'language-spec/exec',
        'language-spec/registry',
        'language-spec/use',
        {
          type: 'category',
          label: 'Functions',
          items: [{type: 'autogenerated', dirName: 'language-spec/functions'}]
        },        
        'language-spec/lexical-structure',
        'language-spec/data-types',
        'language-spec/keywords',
        'language-spec/utility-commands',
      ]
    },  
    {
      type: 'category',
      label: 'Developers',
      items: [{type: 'autogenerated', dirName: 'developers'}]
    },
    {
      type: 'link',
      label: 'Provider Registry',
      href: '/registry',
    },
    {
      type: 'category',
      label: 'GitHub Actions',
      items: [
        {
          type: 'link',
          label: 'setup-stackql',
          href: 'https://github.com/marketplace/actions/stackql-studios-setup-stackql',
        },
        {
          type: 'link',
          label: 'stackql-exec',
          href: 'https://github.com/marketplace/actions/stackql-studios-stackql-exec',
        },
        {
          type: 'link',
          label: 'stackql-assert',
          href: 'https://github.com/marketplace/actions/stackql-studios-stackql-assert',
        },
      ]
    },
    {
      type: 'category',
      label: 'Docker Images',
      items: [
        {
          type: 'link',
          label: 'stackql/stackql',
          href: 'https://hub.docker.com/r/stackql/stackql',
        },
        {
          type: 'link',
          label: 'stackql/stackql-jupyter-demo',
          href: 'https://hub.docker.com/r/stackql/stackql-jupyter-demo',
        },
        {
          type: 'link',
          label: 'stackql/stackql-playground',
          href: 'https://hub.docker.com/r/stackql/stackql-playground',
        },
      ]
    },        
    {
      type: 'category',
      label: 'Python Packages',
      items: [
        {
          type: 'link',
          label: 'pystackql',
          href: 'https://pystackql.readthedocs.io/en/latest/',
        },
      ]
    },    
    {
      type: 'link',
      label: 'Blog',
      href: '/blog',
    },
    {
      type: 'link',
      label: 'Downloads',
      href: '/downloads',
    },    
  ],
};

module.exports = sidebars;
