#!/usr/bin/env python3
"""Compile query library sources into the published artifacts.

Reads query-library/queries/**/*.md and regenerates static/docs/query-library/
wholesale:

  index.json          tool catalogue (search runs over this)
  index.md            human/model readable catalogue
  manifest.json       build_id, timestamp, commit, entry count
  providers.json      site-facing provider summary (title, count, logo)
  queries/<id>.json   parsed front matter + template (tool-facing)
  queries/<id>.md     verbatim copy of the source (raw GitHub fallback tier)

It also generates one MDX stub per provider at query-library/<provider>.mdx
(mounting the ProviderContent React component inside the docs layout, so
provider pages get the query library sidebar); stale stubs for removed
providers are deleted. query-library/index.mdx (the landing page) is
handwritten, not generated.

build_id is a content hash of the compiled library (raw sources + emitted JSON),
not the site build id: it is the MCP server's cache key and must change when and
only when library content changes. manifest.json's generated_at and
library_commit are only rewritten when build_id changes, so re-running this
script on unchanged content is byte-for-byte idempotent (CI relies on this).

Validation runs first; artifacts are never emitted from invalid sources.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import validate
from qlib import (
    LIBRARY_DIR,
    REPO_ROOT,
    SITE_BASE_URL,
    STATIC_OUT_DIR,
    entry_to_doc,
    entry_to_index_entry,
    load_entries,
)

PROVIDER_IMG_DIR = REPO_ROOT / "static" / "img" / "providers"
PROVIDERS_DATA_PATH = REPO_ROOT / "src" / "configs" / "providers-data.json"
STUB_MARKER = "GENERATED by query-library/scripts/build-artifacts.py - do not edit"


def canonical_json(value) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def compute_build_id(entries, docs, index_entries) -> str:
    h = hashlib.sha256()
    for entry, doc in zip(entries, docs):
        h.update(entry.id.encode("utf-8"))
        h.update(b"\0")
        h.update(entry.raw.encode("utf-8"))
        h.update(b"\0")
        h.update(canonical_json(doc).encode("utf-8"))
        h.update(b"\0")
    h.update(canonical_json(index_entries).encode("utf-8"))
    return "ql-" + h.hexdigest()[:16]


def git_short_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def build_manifest(build_id: str, entry_count: int) -> dict:
    manifest_path = STATIC_OUT_DIR / "manifest.json"
    if manifest_path.is_file():
        try:
            existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = {}
        if existing.get("build_id") == build_id:
            # Unchanged content: preserve the manifest verbatim so regeneration
            # is idempotent.
            existing["entry_count"] = entry_count
            return existing
    return {
        "build_id": build_id,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "library_commit": git_short_commit(),
        "entry_count": entry_count,
    }


def load_provider_display() -> dict:
    """Display metadata keyed by provider id, from src/configs/providers-data.json
    (the same source the site components use)."""
    try:
        rows = json.loads(PROVIDERS_DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        rows = []
    return {row["name"]: row for row in rows}


def resolve_logo(provider_id: str) -> str | None:
    """Resolve a logo URL for a provider under static/img/providers/.

    Favicon files win over the full logo so small square marks render in the
    card grid and header; the _account/_workspace suffix falls back to the
    base brand directory (databricks_account uses databricks assets)."""
    candidates = [provider_id]
    stripped = re.sub(r"_(account|workspace)$", "", provider_id)
    if stripped != provider_id:
        candidates.append(stripped)
    for cand in candidates:
        for fname in ("favicon.svg", "favicon.png", "favicon.ico", f"{cand}.png"):
            if (PROVIDER_IMG_DIR / cand / fname).is_file():
                return f"/img/providers/{cand}/{fname}"
    return None


def build_providers_summary(entries) -> list[dict]:
    display = load_provider_display()
    counts: dict[str, int] = {}
    for entry in entries:
        provider_id = entry.id.split("/")[0]
        counts[provider_id] = counts.get(provider_id, 0) + 1
    summary = []
    for provider_id in sorted(counts):
        meta = display.get(provider_id, {})
        title = meta.get("title") or provider_id.replace("_", " ").title()
        summary.append(
            {
                "id": provider_id,
                "title": title,
                "description": meta.get("description")
                or f"Curated StackQL queries for {title}.",
                "count": counts[provider_id],
                "logo": resolve_logo(provider_id),
            }
        )
    return summary


def write_provider_stubs(providers: list[dict]) -> None:
    """Generate query-library/<provider>.mdx docs stubs and remove stale ones.

    Stubs mount the ProviderContent component inside the docs layout so
    provider pages carry the query library sidebar. Only files containing the
    generation marker are ever touched; index.mdx is handwritten."""
    current_ids = {p["id"] for p in providers}
    for p in providers:
        stub_path = LIBRARY_DIR / f"{p['id']}.mdx"
        stub = (
            "---\n"
            f"title: {p['title']} queries\n"
            f"description: \"{p['description'].rstrip('.')} - curated StackQL queries.\"\n"
            "hide_title: true\n"
            "---\n"
            "\n"
            f"{{/* {STUB_MARKER} */}}\n"
            "\n"
            "import ProviderContent from '@site/src/components/QueryLibrary/ProviderContent';\n"
            "\n"
            f"<ProviderContent provider=\"{p['id']}\" />\n"
        )
        stub_path.write_text(stub, encoding="utf-8", newline="\n")
    for existing in LIBRARY_DIR.glob("*.mdx"):
        if existing.stem == "index" or existing.stem in current_ids:
            continue
        if STUB_MARKER in existing.read_text(encoding="utf-8"):
            existing.unlink()


def build_index_md(entries, build_id: str) -> str:
    lines = [
        "# StackQL Query Library",
        "",
        "> Curated, parameterized StackQL queries for common cloud inventory,",
        "> security and operations asks. Each entry has a rendered doc page (HTML),",
        "> a raw Markdown source (`<id>.md`) and a structured JSON document",
        "> (`<id>.json`) consumed by the stackql MCP server's `query_library_search`",
        "> and `query_library_get` tools.",
        "",
        f"Build `{build_id}` | {len(entries)} entries | machine catalogue:",
        f"[index.json]({SITE_BASE_URL}/index.json) |",
        f"[manifest.json]({SITE_BASE_URL}/manifest.json)",
        "",
    ]
    by_provider: dict[str, list] = {}
    for entry in entries:
        provider = entry.id.split("/")[0]
        by_provider.setdefault(provider, []).append(entry)
    for provider in sorted(by_provider):
        lines.append(f"## {provider}")
        lines.append("")
        for entry in by_provider[provider]:
            fm = entry.front_matter
            required = [p["name"] for p in fm.get("params", []) if p.get("required")]
            qualifiers = [fm.get("verb", "select")]
            if fm.get("status") != "stable":
                qualifiers.append(fm.get("status", "draft"))
            if required:
                qualifiers.append("params: " + ", ".join(required))
            lines.append(
                f"- [{fm.get('title', entry.id)}]({entry.doc_url}) "
                f"({'; '.join(qualifiers)}): {fm.get('description', '')}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    if validate.main() != 0:
        print("build-artifacts: validation failed, not emitting artifacts", file=sys.stderr)
        return 1

    entries = load_entries()
    docs = [entry_to_doc(e) for e in entries]
    index_entries = [entry_to_index_entry(e) for e in entries]
    build_id = compute_build_id(entries, docs, index_entries)
    manifest = build_manifest(build_id, len(entries))

    if STATIC_OUT_DIR.exists():
        shutil.rmtree(STATIC_OUT_DIR)
    (STATIC_OUT_DIR / "queries").mkdir(parents=True)

    (STATIC_OUT_DIR / "index.json").write_text(
        canonical_json({"build_id": build_id, "entries": index_entries}),
        encoding="utf-8",
        newline="\n",
    )
    (STATIC_OUT_DIR / "manifest.json").write_text(
        canonical_json(manifest), encoding="utf-8", newline="\n"
    )
    (STATIC_OUT_DIR / "index.md").write_text(
        build_index_md(entries, build_id), encoding="utf-8", newline="\n"
    )
    # Site-facing extras: not part of the frozen machine contract and not
    # hashed into build_id (presentation data only).
    providers_summary = build_providers_summary(entries)
    (STATIC_OUT_DIR / "providers.json").write_text(
        canonical_json(providers_summary), encoding="utf-8", newline="\n"
    )
    write_provider_stubs(providers_summary)
    for entry, doc in zip(entries, docs):
        out_json = STATIC_OUT_DIR / "queries" / f"{entry.id}.json"
        out_md = STATIC_OUT_DIR / "queries" / f"{entry.id}.md"
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(canonical_json(doc), encoding="utf-8", newline="\n")
        out_md.write_text(entry.raw, encoding="utf-8", newline="\n")

    print(
        f"built {len(entries)} entries -> {STATIC_OUT_DIR.relative_to(REPO_ROOT)} "
        f"(build_id {build_id})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
